{"name": "test_dept_delete", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100 == 101\n  +100\n  -101", "trace": "self = <case.test_03_dept.TestDept object at 0x00000241A11447C0>, args = ()\nkwargs = {}\n\n    def inner(self, *args, **kwargs):\n        try:\n>           fun(self, *args, **kwargs)\n\ncase\\test_03_dept.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <case.test_03_dept.TestDept object at 0x00000241A11447C0>\n\n    @wrapper_error\n    def test_dept_delete(self):\n        origin_count = self.dept.get_total_size()\n        self.dept.delete_dept()\n        delete_count = self.dept.get_total_size()\n>       assert origin_count == delete_count + 1\nE       assert 100 == 101\nE         +100\nE         -101\n\ncase\\test_03_dept.py:49: AssertionError"}, "start": 1640179479957, "stop": 1640179480617, "uuid": "2a549101-ec2e-445a-86b3-13d11590f9fe", "historyId": "698ebf27ba51629d6d2a7fea9c885ae4", "testCaseId": "12d6226d0080c9311440846c57c83123", "fullName": "case.test_03_dept.TestDept#test_dept_delete", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_03_dept"}, {"name": "subSuite", "value": "TestDept"}, {"name": "host", "value": "DESKTOP-PBBG206"}, {"name": "thread", "value": "3452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_03_dept"}]}